name: 'dormant-repos'
description: 'Dormant repos'
inputs:
  token:
    description: 'A Personal Access token with admin:org scope'
    required: true
  org:
    description: 'Custom GitHub organization to retrieve data for'
    default: ${{ github.repository_owner }}
    required: false
  adminTeamName:
    required: true
    description: 'Which repos is this an admin team of'
runs:
  using: 'node16'
  main: 'dist/index.js'
